import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import {RiMoonFoggyFill} from 'react-icons/ri'
import "./index.scss";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Rohit Nair Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <section className="min-h-screen">
            <nav className="p-10">
              <h1>
                Rohit Nair
              </h1>
              <ul>
                <li>
                  <RiMoonFoggyFill />
                </li>
                <li>
                  <a href="#">
                    Resume
                  </a>
                </li>
              </ul>
        
            </nav>
          </section>
        </div>
      </main>
    </>
  )
}
